const nonPaymentData = () => {
  const nonPaymentHeader = {
    num: "번호",
    reportDateTime: "신고일시",
    orderringCompany: "발주사",
    companyName: "업체명",
    name: "이름",
    equipmentBusinessOperator: "장비사업자",
    equipmentBusinessOperatorCompanyName: "업체명",
    equipmentBusinessOperatorName: "이름",
    reportDetails: "신고내용",
    situation: "상태",
    viewChat: "채팅보기",
    viewContract: "계약서보기",
    image: "이미지",
  };
  const nonPaymentDataContent = [
    {
      num: 4,
      reportDateTime: "2022.05.12  17:35",
      companyName: "센트오브필라",
      name: "이중재",
      equipmentCompanyName: "센트오브필라",
      equipmentName: "이중재",
      reportDetails: "~~~욕을 해요",
      situation: "대기",
      viewChat: "확인",
      viewContract: "확인",
      pictures: 2,
    },
    {
      num: 3,
      reportDateTime: "2022.05.10  02:21",
      companyName: "HH필라테스",
      name: "이중재",
      equipmentCompanyName: "HH필라테스",
      equipmentName: "이중재",
      reportDetails: "~~~욕을 해요",
      situation: "대기",
      viewChat: "확인",
      viewContract: "확인",
      pictures: 0,
    },
    {
      num: 2,
      reportDateTime: "2022.05.09  19:21",
      companyName: "헤어메이크샵",
      name: "이중재",
      equipmentCompanyName: "헤어메이크샵",
      equipmentName: "이중재",
      reportDetails: "~~~욕을 해요",
      situation: "체불확인",
      viewChat: "확인",
      viewContract: "확인",
      pictures: 2,
    },
    {
      num: 1,
      reportDateTime: "2022.05.07  21:11",
      companyName: "라운드헤어샵",
      name: "이중재",
      equipmentCompanyName: "센트오브필라",
      equipmentName: "이중재",
      reportDetails: "~~~욕을 해요",
      situation: "보류",
      viewChat: "확인",
      viewContract: "확인",
      pictures: 0,
    },
  ];
  return { nonPaymentHeader, nonPaymentDataContent };
};

export default nonPaymentData;
